/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PeminjamRouteRouteImport } from './routes/peminjam/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PeminjamIndexRouteImport } from './routes/peminjam/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as PeminjamCekPeminjamanRouteImport } from './routes/peminjam/cek-peminjaman'
import { Route as AdminPeminjamanRuangRouteImport } from './routes/admin/peminjaman-ruang'
import { Route as AdminManajemenUserRouteImport } from './routes/admin/manajemen-user'
import { Route as AdminManajemenRuangRouteImport } from './routes/admin/manajemen-ruang'
import { Route as AdminManajemenPeminjamanRouteImport } from './routes/admin/manajemen-peminjaman'
import { Route as AdminApproval_sumberdayaRouteImport } from './routes/admin/approval_sumberdaya'
import { Route as AdminApproval_kemahasiswaanRouteImport } from './routes/admin/approval_kemahasiswaan'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PeminjamRouteRoute = PeminjamRouteRouteImport.update({
  id: '/peminjam',
  path: '/peminjam',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PeminjamIndexRoute = PeminjamIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PeminjamRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const PeminjamCekPeminjamanRoute = PeminjamCekPeminjamanRouteImport.update({
  id: '/cek-peminjaman',
  path: '/cek-peminjaman',
  getParentRoute: () => PeminjamRouteRoute,
} as any)
const AdminPeminjamanRuangRoute = AdminPeminjamanRuangRouteImport.update({
  id: '/peminjaman-ruang',
  path: '/peminjaman-ruang',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminManajemenUserRoute = AdminManajemenUserRouteImport.update({
  id: '/manajemen-user',
  path: '/manajemen-user',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminManajemenRuangRoute = AdminManajemenRuangRouteImport.update({
  id: '/manajemen-ruang',
  path: '/manajemen-ruang',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminManajemenPeminjamanRoute =
  AdminManajemenPeminjamanRouteImport.update({
    id: '/manajemen-peminjaman',
    path: '/manajemen-peminjaman',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminApproval_sumberdayaRoute =
  AdminApproval_sumberdayaRouteImport.update({
    id: '/approval_sumberdaya',
    path: '/approval_sumberdaya',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminApproval_kemahasiswaanRoute =
  AdminApproval_kemahasiswaanRouteImport.update({
    id: '/approval_kemahasiswaan',
    path: '/approval_kemahasiswaan',
    getParentRoute: () => AdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/peminjam': typeof PeminjamRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/approval_kemahasiswaan': typeof AdminApproval_kemahasiswaanRoute
  '/admin/approval_sumberdaya': typeof AdminApproval_sumberdayaRoute
  '/admin/manajemen-peminjaman': typeof AdminManajemenPeminjamanRoute
  '/admin/manajemen-ruang': typeof AdminManajemenRuangRoute
  '/admin/manajemen-user': typeof AdminManajemenUserRoute
  '/admin/peminjaman-ruang': typeof AdminPeminjamanRuangRoute
  '/peminjam/cek-peminjaman': typeof PeminjamCekPeminjamanRoute
  '/admin/': typeof AdminIndexRoute
  '/peminjam/': typeof PeminjamIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/approval_kemahasiswaan': typeof AdminApproval_kemahasiswaanRoute
  '/admin/approval_sumberdaya': typeof AdminApproval_sumberdayaRoute
  '/admin/manajemen-peminjaman': typeof AdminManajemenPeminjamanRoute
  '/admin/manajemen-ruang': typeof AdminManajemenRuangRoute
  '/admin/manajemen-user': typeof AdminManajemenUserRoute
  '/admin/peminjaman-ruang': typeof AdminPeminjamanRuangRoute
  '/peminjam/cek-peminjaman': typeof PeminjamCekPeminjamanRoute
  '/admin': typeof AdminIndexRoute
  '/peminjam': typeof PeminjamIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/peminjam': typeof PeminjamRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/approval_kemahasiswaan': typeof AdminApproval_kemahasiswaanRoute
  '/admin/approval_sumberdaya': typeof AdminApproval_sumberdayaRoute
  '/admin/manajemen-peminjaman': typeof AdminManajemenPeminjamanRoute
  '/admin/manajemen-ruang': typeof AdminManajemenRuangRoute
  '/admin/manajemen-user': typeof AdminManajemenUserRoute
  '/admin/peminjaman-ruang': typeof AdminPeminjamanRuangRoute
  '/peminjam/cek-peminjaman': typeof PeminjamCekPeminjamanRoute
  '/admin/': typeof AdminIndexRoute
  '/peminjam/': typeof PeminjamIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/peminjam'
    | '/login'
    | '/admin/approval_kemahasiswaan'
    | '/admin/approval_sumberdaya'
    | '/admin/manajemen-peminjaman'
    | '/admin/manajemen-ruang'
    | '/admin/manajemen-user'
    | '/admin/peminjaman-ruang'
    | '/peminjam/cek-peminjaman'
    | '/admin/'
    | '/peminjam/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/approval_kemahasiswaan'
    | '/admin/approval_sumberdaya'
    | '/admin/manajemen-peminjaman'
    | '/admin/manajemen-ruang'
    | '/admin/manajemen-user'
    | '/admin/peminjaman-ruang'
    | '/peminjam/cek-peminjaman'
    | '/admin'
    | '/peminjam'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/peminjam'
    | '/login'
    | '/admin/approval_kemahasiswaan'
    | '/admin/approval_sumberdaya'
    | '/admin/manajemen-peminjaman'
    | '/admin/manajemen-ruang'
    | '/admin/manajemen-user'
    | '/admin/peminjaman-ruang'
    | '/peminjam/cek-peminjaman'
    | '/admin/'
    | '/peminjam/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  PeminjamRouteRoute: typeof PeminjamRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/peminjam': {
      id: '/peminjam'
      path: '/peminjam'
      fullPath: '/peminjam'
      preLoaderRoute: typeof PeminjamRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/peminjam/': {
      id: '/peminjam/'
      path: '/'
      fullPath: '/peminjam/'
      preLoaderRoute: typeof PeminjamIndexRouteImport
      parentRoute: typeof PeminjamRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/peminjam/cek-peminjaman': {
      id: '/peminjam/cek-peminjaman'
      path: '/cek-peminjaman'
      fullPath: '/peminjam/cek-peminjaman'
      preLoaderRoute: typeof PeminjamCekPeminjamanRouteImport
      parentRoute: typeof PeminjamRouteRoute
    }
    '/admin/peminjaman-ruang': {
      id: '/admin/peminjaman-ruang'
      path: '/peminjaman-ruang'
      fullPath: '/admin/peminjaman-ruang'
      preLoaderRoute: typeof AdminPeminjamanRuangRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/manajemen-user': {
      id: '/admin/manajemen-user'
      path: '/manajemen-user'
      fullPath: '/admin/manajemen-user'
      preLoaderRoute: typeof AdminManajemenUserRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/manajemen-ruang': {
      id: '/admin/manajemen-ruang'
      path: '/manajemen-ruang'
      fullPath: '/admin/manajemen-ruang'
      preLoaderRoute: typeof AdminManajemenRuangRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/manajemen-peminjaman': {
      id: '/admin/manajemen-peminjaman'
      path: '/manajemen-peminjaman'
      fullPath: '/admin/manajemen-peminjaman'
      preLoaderRoute: typeof AdminManajemenPeminjamanRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/approval_sumberdaya': {
      id: '/admin/approval_sumberdaya'
      path: '/approval_sumberdaya'
      fullPath: '/admin/approval_sumberdaya'
      preLoaderRoute: typeof AdminApproval_sumberdayaRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/approval_kemahasiswaan': {
      id: '/admin/approval_kemahasiswaan'
      path: '/approval_kemahasiswaan'
      fullPath: '/admin/approval_kemahasiswaan'
      preLoaderRoute: typeof AdminApproval_kemahasiswaanRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminApproval_kemahasiswaanRoute: typeof AdminApproval_kemahasiswaanRoute
  AdminApproval_sumberdayaRoute: typeof AdminApproval_sumberdayaRoute
  AdminManajemenPeminjamanRoute: typeof AdminManajemenPeminjamanRoute
  AdminManajemenRuangRoute: typeof AdminManajemenRuangRoute
  AdminManajemenUserRoute: typeof AdminManajemenUserRoute
  AdminPeminjamanRuangRoute: typeof AdminPeminjamanRuangRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminApproval_kemahasiswaanRoute: AdminApproval_kemahasiswaanRoute,
  AdminApproval_sumberdayaRoute: AdminApproval_sumberdayaRoute,
  AdminManajemenPeminjamanRoute: AdminManajemenPeminjamanRoute,
  AdminManajemenRuangRoute: AdminManajemenRuangRoute,
  AdminManajemenUserRoute: AdminManajemenUserRoute,
  AdminPeminjamanRuangRoute: AdminPeminjamanRuangRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface PeminjamRouteRouteChildren {
  PeminjamCekPeminjamanRoute: typeof PeminjamCekPeminjamanRoute
  PeminjamIndexRoute: typeof PeminjamIndexRoute
}

const PeminjamRouteRouteChildren: PeminjamRouteRouteChildren = {
  PeminjamCekPeminjamanRoute: PeminjamCekPeminjamanRoute,
  PeminjamIndexRoute: PeminjamIndexRoute,
}

const PeminjamRouteRouteWithChildren = PeminjamRouteRoute._addFileChildren(
  PeminjamRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  PeminjamRouteRoute: PeminjamRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
